kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: terrascan-webhook-deleter
  namespace: terrascan
subjects:
  - kind: ServiceAccount
    name: terrascan-webhook-deleter-job-sa
    namespace: terrascan
roleRef:
  kind: ClusterRole
  name: terrascan-webhook-delete-only
  apiGroup: rbac.authorization.k8s.io
