# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: terrascan
    id: terrascan_darwin
    main: ./cmd/terrascan/main.go
    ldflags: -s -w
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
    flags:
      - -buildmode
      - exe
      - -tags
      - extended
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
checksum:
  name_template: 'checksum_darwin.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
