apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: terrahook
webhooks:
  - name: www.terrahook.com
    admissionReviewVersions: ["v1","v1beta1"]
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: terrahook
        namespace: terrascan
        path: "/v1/k8s/webhooks/terrakey/scan/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR5ekNDQXJPZ0F3SUJBZ0lKQU1JTE5WZFN6UklCTUEwR0NTcUdTSWIzRFFFQkN3VUFNSUdRTVFzd0NRWUQKVlFRR0V3SkpUakVVTUJJR0ExVUVDQXdMVFdGb1lYSmhjMmgwY21FeERUQUxCZ05WQkFjTUJGQjFibVV4RVRBUApCZ05WQkFvTUNFRmpZM1Z5YVdOek1TY3dKUVlKS29aSWh2Y05BUWtCRmhoa1pYWmhibWN1WjJGMWNrQmhZMk4xCmNtbGpjeTVqYjIweElEQWVCZ05WQkFNTUYzUmxjbkpoYUc5dmF5NTBaWEp5WVhOallXNHVjM1pqTUI0WERUSXgKTURReE1qRTFOVEV3TVZvWERUSXhNRFV4TWpFMU5URXdNVm93Z1pBeEN6QUpCZ05WQkFZVEFrbE9NUlF3RWdZRApWUVFJREF0TllXaGhjbUZ6YUhSeVlURU5NQXNHQTFVRUJ3d0VVSFZ1WlRFUk1BOEdBMVVFQ2d3SVFXTmpkWEpwClkzTXhKekFsQmdrcWhraUc5dzBCQ1FFV0dHUmxkbUZ1Wnk1bllYVnlRR0ZqWTNWeWFXTnpMbU52YlRFZ01CNEcKQTFVRUF3d1hkR1Z5Y21Gb2IyOXJMblJsY25KaGMyTmhiaTV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFDNDJlWGp1MEFNekZTNUNxWUsyQThJZ2tTbTJjSDZ6b1R3V0xIWnZsTnVuVkxCClBkcWRrR1ZnR0RZeXJLRVJ2TWZDSVRxT1BKeXR1ODc0Q2xIUGxvVXVwQkVJQms2ZEJ1Ull5dzU1SUlSS3Vta0oKUHByaC9JUUpoajJmV2t4ZUFkYUhLNEl6YVp3VFpkWFE2OEdQQUdZTUVRRUhxR2pEOU91cFBXdldKT3RoVUkzUgpEMnhWUnRlRXJYZ0ZRQ01DQUVEQ21WOUJ1UWlYYkFPMDVFaUtDMjRmZm5hK1ZFOU9yaStnOEgvYlRPMmpxN1ZaClV4LzhmczhyUVlRV3JyVExrRUZVckJUSVhPS2dLcFhTNUQwYU5xaC9POWQxY0VrUzJ0Q25ZM20wV0sxZXhabkUKUGdSRlRiUUVpT3lBRmZUT1JGbERld3RxZWJIWExkMnBVLzNGTXdsVEFnTUJBQUdqSmpBa01DSUdBMVVkRVFRYgpNQm1DRjNSbGNuSmhhRzl2YXk1MFpYSnlZWE5qWVc0dWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFTCjhGR3JtUWRRVkNjNDI3MGZTMkpEMHV4blJDaFJXNWJORG9pazdZZ3gwalRxanFKdVRTai9BdXQwbUZzSk9DSjMKL3o3VFFBRFBCSFpSdlhUWFNIWG84K1MvLytsUDd5YWtjSitlR0dvUEpHWktXVWFDdTlyZU1XSkJ2OVVSbnl6UwphN01hSy8vb0U0UkZmT0dJMm5sRG9FZ0FydGpZOVUzYmlwWUdwR0orSVcxN1l1akM1LzB1MUNEdzlMNDRiZ1lFCm1yaTBOckFWSnJyeHpqUDVHd2ZvZ0h0L1NnaVZPZ2hOVTRsUE9uWGx5SVd6OVJoN1JIL3JRNnl5VkRrTjU4ZFQKNWFsMkdMTk9GSnJkRG0vQWN5YzVqaWZzSWVuNnV3aElZNWI0VU42Yk92MkdyWXZ4RXhrVXZHaE1BdWF3UVdiWgpVVWt5VUFlSlk3SHJkb1lCMlRpSwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - apiGroups: ["apps", ""]
        resources:
          - "deployments"
          - "pods"
        apiVersions:
          - "*"
        operations:
          - CREATE
