apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  key: |-
    {{ .Files.Get "data/server.key" | b64enc }}
  cert: |-
    {{ .Files.Get "data/server.crt" | b64enc }}
